/* =====================================================================
   Menu data — single source of truth for dishes across the site.
   Prices in Nigerian Naira (₦).
   tags: veg | spicy | gf | pop  (pop = popular)
   ===================================================================== */
window.MENU = [
  {
    id: "jollof-chicken",
    name: "Jollof Rice & Chicken",
    cat: "rice",
    price: 3500,
    img: "images/jollof rice and chicken.avif",
    desc: "Our signature smoky party jollof, slow-cooked in rich tomato base, served with grilled chicken.",
    tags: ["pop", "gf"],
    rating: 4.9, reviews: 214,
  },
  {
    id: "ofada-ayamase",
    name: "Ofada Rice & Ayamase",
    cat: "rice",
    price: 3800,
    img: "images/ofada rice.webp",
    desc: "Local unpolished ofada rice paired with fiery green pepper (ayamase) stew and assorted meat.",
    tags: ["spicy", "gf"],
    rating: 4.7, reviews: 96,
  },
  {
    id: "fried-rice",
    name: "Nigerian Fried Rice",
    cat: "rice",
    price: 3600,
    img: "images/fried-rice.jpg",
    desc: "Vegetable-packed fried rice with liver, shrimp and sweet peppers, wok-tossed to perfection.",
    tags: ["pop"],
    rating: 4.6, reviews: 88,
  },
  {
    id: "party-jollof",
    name: "Party Jollof (Large Tray)",
    cat: "rice",
    price: 12000,
    img: "images/Nigeria-Jollof-rice.jpg",
    desc: "A generous sharing tray of our famous smoky jollof — feeds 4–6. Perfect for gatherings.",
    tags: ["pop"],
    rating: 5.0, reviews: 51,
  },
  {
    id: "pounded-yam-egusi",
    name: "Pounded Yam & Egusi",
    cat: "swallow",
    price: 4200,
    img: "images/pounded yam and egusi.jpg",
    desc: "Smooth hand-pounded yam served with rich melon-seed egusi soup loaded with meat and fish.",
    tags: ["pop", "gf"],
    rating: 4.9, reviews: 176,
  },
  {
    id: "amala-ewedu",
    name: "Amala & Ewedu",
    cat: "swallow",
    price: 3500,
    img: "images/amala and ewedu.webp",
    desc: "Soft yam-flour amala with silky ewedu and gbegiri, topped with peppery obe ata stew.",
    tags: ["gf"],
    rating: 4.8, reviews: 132,
  },
  {
    id: "amala-gbegiri",
    name: "Amala & Abula",
    cat: "swallow",
    price: 3900,
    img: "images/amala.jpg",
    desc: "The full abula experience — amala with gbegiri (beans), ewedu and assorted goat meat.",
    tags: ["gf"],
    rating: 4.7, reviews: 74,
  },
  {
    id: "plantain-sauce",
    name: "Fried Plantain & Sauce",
    cat: "sides",
    price: 2000,
    img: "images/fried plantain and sauce.webp",
    desc: "Sweet ripe dodo fried golden, served with a spicy pepper egg sauce. Comfort in a bowl.",
    tags: ["veg", "spicy"],
    rating: 4.8, reviews: 143,
  },
  {
    id: "puff-puff",
    name: "Puff Puff (6 pcs)",
    cat: "sides",
    price: 1500,
    img: "images/puff-puff.jpg",
    desc: "Fluffy deep-fried dough balls dusted lightly with sugar — Nigeria's favourite street snack.",
    tags: ["veg"],
    rating: 4.9, reviews: 121,
  },
  {
    id: "suya",
    name: "Beef Suya Skewers",
    cat: "grills",
    price: 3200,
    img: "images/suya.jpg",
    desc: "Thin-sliced beef marinated in yaji spice, char-grilled and served with onions & tomatoes.",
    tags: ["spicy", "gf", "pop"],
    rating: 4.9, reviews: 189,
  },
  {
    id: "peppered-chicken",
    name: "Peppered Chicken",
    cat: "grills",
    price: 4000,
    img: "images/peppered-chicken.jpg",
    desc: "Juicy chicken pieces tossed in a smoky, spicy pepper sauce with caramelised onions.",
    tags: ["spicy", "gf"],
    rating: 4.8, reviews: 108,
  },
  {
    id: "assorted-platter",
    name: "Chef's Assorted Platter",
    cat: "grills",
    price: 6500,
    img: "images/OIP.webp",
    desc: "A curated tasting board of suya, peppered gizzard, plantain and small chops. Great to share.",
    tags: ["pop", "spicy"],
    rating: 5.0, reviews: 63,
  },
];

/* Category metadata for filters */
window.MENU_CATS = [
  { id: "all",     label: "All Dishes" },
  { id: "rice",    label: "Rice Dishes" },
  { id: "swallow", label: "Swallow & Soups" },
  { id: "grills",  label: "Grills & Proteins" },
  { id: "sides",   label: "Snacks & Sides" },
];
